app:
  build: .
  command: "bundle exec rails s -b 0.0.0.0"
  env_file: .env
  environment:
    - DATABASE_HOST=db
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=
    - DATABASE_NAME=postgres
    - REDIS_URL=redis://redis:6379
    - GEM_HOME=/bundle
  volumes:
    - .:/decidim.barcelona
  volumes_from:
    - bundle
  links:
    - db
    - redis
  ports:
    - "3000:3000"

sidekiq:
  image: decidimbarcelona_app
  command: bundle exec sidekiq
  environment:
    - DATABASE_HOST=db
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=
    - DATABASE_NAME=postgres
    - REDIS_URL=redis://redis:6379
    - GEM_HOME=/bundle
  volumes:
    - .:/decidim.barcelona
  volumes_from:
    - bundle
  links:
    - db
    - redis

webpack:
  image: decidimbarcelona_app
  command: webpack --watch --colors
  volumes:
    - .:/decidim.barcelona

bundle:
  image: decidimbarcelona_app
  command: echo 'Nothing to do here'
  volumes:
    - .bundle:/bundle

db:
  image: postgres
  volumes:
    - .postgres_data:/var/lib/postgresql/data

redis:
  image: redis
  volumes:
    - .redis_data:/data
