defaults: &defaults
  # Org name of the website.
  org_name: "decidim.barcelona"

  # City or organization.
  place_name: "Barcelona"

  # Names for the moderation console, as a hint for moderators
  # to know better how to assign users with official positions
  official_level_1_name: "Empleados públicos"
  official_level_2_name: "Organización Municipal"
  official_level_3_name: "Directores generales"
  official_level_4_name: "Concejales"
  official_level_5_name: "Alcaldesa"

  # Max percentage of allowed anonymous votes on a debate
  max_ratio_anon_votes_on_debates: 50

  # Max votes where a debate is still editable
  max_votes_for_debate_edit: 1000

  # Max votes where a proposal is still editable
  max_votes_for_proposal_edit: 10

  # Prefix for the Proposal codes
  proposal_code_prefix: 'BCN'

  # Prefix for the Proposal codes
  meeting_code_prefix: 'BCN-M'

  # Number of votes needed for proposal success
  votes_for_proposal_success: 100

  # Users with this email domain will automatically be marked as level 1 officials
  # Emails under the domain's subdomains will also be included
  email_domain_for_officials: ''

  twitter_handle: "bcn_ajuntament"
  facebook_handle: "bcn.cat"
  youtube_handle: "bcnajuntament"
  instagram_handle: "barcelona_cat"
  github_handle: "AjuntamentdeBarcelona/decidim.barcelona"
  facebook_app_id: "929041747208547"

  proposal_closing_time: <%= ENV['PROPOSAL_CLOSING_DATE'] ? Time.zone.parse(ENV['PROPOSAL_CLOSING_DATE']) : nil %>

  blog_url: 
    ca: "http://eldigital.barcelona.cat/pambcn"
    es: "http://eldigital.barcelona.cat/es/pambcn_es"
    en: "http://eldigital.barcelona.cat/en/pambcn_en"

  url: "https://decidim.barcelona"

  # Users with this email domain will automatically be marked as level 1 officials
  # Emails under the domain's subdomains will also be included
  email_domain_for_officials: ''

  # Code to be included at the top (header) of every page (useful for tracking)
  per_page_code: ''

  feature.debates: true
  feature.debates.vote: false
  feature.debates.search: false
  feature.spending_proposals: false
  feature.proposal_tags: false
  feature.proposal_video_url: false
  feature.meeting_tags: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
